sudo: false
dist: trusty
language: cpp

git:
  submodules: true

cache:
  apt: true
  ccache: true

linux-gcc-7: &linux-gcc-7
  os: linux
  compiler: 'g++-7'
  addons:
    apt:
      sources: ['ubuntu-toolchain-r-test']
      packages: ['g++-7']
  before_install:
    - export CC="gcc-7" CXX="g++-7"

# https://docs.travis-ci.com/user/languages/c/#gcc-on-linux
matrix:
  include:
  - << : *linux-gcc-7
    env:
      - BUILD=unit
      - BUILD_TYPE=Release
  - << : *linux-gcc-7
    env:
      - BUILD=unit
      - BUILD_TYPE=Debug
  - << : *linux-gcc-7
    env:
      - BUILD=performance
      - BUILD_TYPE=Release
  - << : *linux-gcc-7
    env:
      - BUILD=performance
      - BUILD_TYPE=Debug

install:
  - ccache --version
  - $CXX -v
  - cmake --version

before_script:
  - mkdir ../seqan3-build
  - cd ../seqan3-build
  - cmake ../seqan3/test/${BUILD} -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
  - |
    if test test = "${BUILD}"; then
      make googletest
    fi
  - |
    if test benchmark = "${BUILD}"; then
      make google_benchmark
    fi

script:
  - make -k
  - ctest . --output-on-failure

after_script:
  - ccache -s
